version: '3'
services:
  coordinator:
    image: citusdata/citus:11.2
    platform: linux/amd64
    container_name: sicar-coordinator
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    ports:
      - "5432:5432"
    volumes:
      - ./init-citus.sh:/docker-entrypoint-initdb.d/init-citus.sh
      - ./data:/data
    networks:
      - sicar_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raulfelipecarvalho -h localhost || exit 1"]

  worker-1:
    image: citusdata/citus:11.2
    platform: linux/amd64
    container_name: sicar-worker-1
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    volumes:
      - ./init-citus.sh:/docker-entrypoint-initdb.d/init-citus.sh
      - ./data:/data
    networks:
      - sicar_network

  worker-2:
    image: citusdata/citus:11.2
    platform: linux/amd64
    container_name: sicar-worker-2
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    volumes:
      - ./init-citus.sh:/docker-entrypoint-initdb.d/init-citus.sh
      - ./data:/data
    networks:
      - sicar_network

  worker-3:
    image: citusdata/citus:11.2
    platform: linux/amd64
    container_name: sicar-worker-3
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
    volumes:
      - ./init-citus.sh:/docker-entrypoint-initdb.d/init-citus.sh
      - ./data:/data
    networks:
      - sicar_network

networks:
  sicar_network:
    driver: bridge
